springdoc:
  swagger-ui:
    enabled: ${SWAGGER_ENABLED:false}

logging:
  level:    
    org:
      springframework:
        kafka:
          transaction.KafkaTransactionManager: ${LOG_KAFKA_TM_LEVEL:INFO}
        transaction: ${LOG_KAFKA_TM_LEVEL:INFO}
        orm.jpa.JpaTransactionManager: ${LOG_KAFKA_TM_LEVEL:INFO}
      apache.kafka.clients.producer.internals.TransactionManager: ${LOG_KAFKA_TM_LEVEL:INFO}
    root: ${LOG_ROOT_LEVEL}

properties:
  used: "Git-Profiler-dev-application-properties"
