spring:
  servlet:
    multipart:
      file-size-threshold: 2048
      max-file-size: 5MB
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  liquibase:
    change-log: db.changelog/changelog.xml
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: true
    properties:
      jakarta:
        persistence:
          sharedCache:
            mode: UNSPECIFIED
  jackson:
    deserialization:
      fail-on-unknown-properties: true
  main:
    banner-mode: "off"
management:
  endpoints:
    web:
      exposure:
        include: health, info
logging:
  level:
    root: info
    by.javaguru.profiler: debug
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

image:
  storage-dir: ${IMAGES_STORAGE_FOLDER}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

properties:
  used: "Git-Profiler-default-application-properties"
