spring:  
  cloud:   
    httpclient:
      hc5:
        enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: validate
    open-in-view: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: ${SERVER_PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: mapping, bus-refresh,bus-env,health,circuitbreakerevents,retry
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true

resilience4j:
  circuitbreaker:
    configs:
      default:
        failure-rate-threshold: 50
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state:
          seconds: 5
        sliding-window-type: count_based
        sliding-window-size: 2
        minimum-number-of-calls: 1
        event-consumer-buffer-size: 10
        register-health-indicator: true
        permitted-number-of-calls-in-half-open-state: 3
    instances:
      accounting-service:
        base-config: default
      resources-service:
        base-config: default
      profiler-service:
        base-config: default
    circuit-breaker-aspect-order: 1

  retry:
    retry-aspect-order: 2
    configs:
      default:
        max-attempts: 10
        wait-duration:
          seconds: 5
    instances:
      accounting-service:
        base-config: default
      resources-service:
        base-config: default
      profiler-service:
        base-config: default

properties:
  used: "Git-repository-application-properties"
