spring:
  application:
    name: VACATION-SERVICE  
    httpclient:
      hc5:
        enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: validate
    open-in-view: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  kafka:
    producer:
      bootstrap-servers: localhost:9092,localhost:9094
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      #      retries: 10

      properties:
        #        retry.backoff.ms: 1000
        delivery.timeout.ms: 20000
        linger.ms: 0
        request.timeout.ms: 5000
        max.in.flight.requests.per.connection: 5
      acks: all

    consumer:
      bootstrap-servers: localhost:9092,localhost:9094
      group-id: request-created-events

      properties:
        spring.json.trusted.packages: "by.javaguru.jdmik6.core"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: ${SERVER_PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: mapping, bus-refresh,bus-env,health,circuitbreakerevents,retry
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true

resilience4j:
  circuitbreaker:
    configs:
      default:
        failure-rate-threshold: 50
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 15s
        sliding-window-type: count_based
        sliding-window-size: 10
        minimum-number-of-calls: 5
        event-consumer-buffer-size: 10
        register-health-indicator: true
        permitted-number-of-calls-in-half-open-state: 2
    instances:
      accounting-service:
        base-config: default
      resources-service:
        base-config: default
      profiler-service:
        base-config: default
    circuit-breaker-aspect-order: 1

  retry:
    retry-aspect-order: 2
    configs:
      default:
        max-attempts: 3
        wait-duration: 2s
        retry-exceptions:
          - by.javaguru.jdmik6.vacationservice.exception.ServiceConnectionException
          - feign.RetryableException
        ignore-exceptions:
          - by.javaguru.jdmik6.vacationservice.exception.ClientRequestException
          - by.javaguru.jdmik6.vacationservice.exception.NotFoundException
          - by.javaguru.jdmik6.vacationservice.exception.ProfilerUpdateRejectException
          - by.javaguru.jdmik6.vacationservice.exception.BudgetAllocationRejectException
          - by.javaguru.jdmik6.vacationservice.exception.ResourcesCheckRejectException
          - by.javaguru.jdmik6.vacationservice.exception.StabilityMechanismException
    instances:
      accounting-service:
        base-config: default
      resources-service:
        base-config: default
      profiler-service:
        base-config: default

properties:
  used: "Git-Vacation-application-properties"
