spring:
  application:
    name: VACATION-SERVICE
  config:
    import: "optional:configserver:"  
    httpclient:
      hc5:
        enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: validate
    open-in-view: true
    properties.hibernate:
      show_sql: true
#      format_sql: true
      use_sql_comments: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  kafka:
    producer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_PRODUCER_SERVERS}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        delivery.timeout.ms: ${KAFKA_DELIVERY_TIMEOUT_MS:20000}
        linger.ms: ${KAFKA_LINGER_MS:0}
        request.timeout.ms: ${KAFKA_REQUEST_TIMEOUT_MS:5000}
        max.in.flight.requests.per.connection: ${KAFKA_MAX_IN_FLIGHT_REQUESTS_PER_CONNECTION:5}
        spring.json.add.type.headers: true
      acks: ${KAFKA_ACKS:all}
      transaction-id-prefix: vacation-service-${random.value}-

    consumer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_CONSUMER_SERVERS}
      group-id: ${KAFKA_CONSUMER_GROUP_ID:profiler-request-events}
      isolation-level: READ_COMMITTED
      auto-offset-reset: latest

      properties:
        spring.json.trusted.packages: by.javaguru.jdmik6.core.event,by.javaguru.jdmik6.core.enums,by.javaguru.jdmik6.core.util.*

kafka:
  cluster:
    partitions: ${KAFKA_CLUSTER_PARTITIONS:3}
    replicas: ${KAFKA_CLUSTER_REPLICAS:3}
    min-insync-replicas: ${KAFKA_CLUSTER_INSYNC_REPLICAS:2}

logging:
  level:
    org:
      springframework:
        kafka:
          transaction.KafkaTransactionManager: ${LOG_KAFKA_TM_LEVEL:INFO}
        transaction: ${LOG_KAFKA_TM_LEVEL:INFO}
        orm.jpa.JpaTransactionManager: ${LOG_KAFKA_TM_LEVEL:INFO}
      apache.kafka.clients.producer.internals.TransactionManager: ${LOG_KAFKA_TM_LEVEL:INFO}
    root: ${LOG_ROOT_LEVEL:INFO}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: ${SERVER_PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: mapping, bus-refresh,bus-env,health,circuitbreakerevents,retry
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true

resilience4j:
  circuitbreaker:
    configs:
      default:
        failure-rate-threshold: 50
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 15s
        sliding-window-type: count_based
        sliding-window-size: 10
        minimum-number-of-calls: 5
        event-consumer-buffer-size: 10
        register-health-indicator: true
        permitted-number-of-calls-in-half-open-state: 2
    instances:
      accounting-service:
        base-config: default
      resources-service:
        base-config: default
      profiler-service:
        base-config: default
    circuit-breaker-aspect-order: 1

  retry:
    retry-aspect-order: 2
    configs:
      default:
        max-attempts: 3
        wait-duration: 2s
        retry-exceptions:
          - by.javaguru.jdmik6.vacationservice.exception.ServiceConnectionException
          - feign.RetryableException
        ignore-exceptions:
          - by.javaguru.jdmik6.vacationservice.exception.ClientRequestException
          - by.javaguru.jdmik6.vacationservice.exception.NotFoundException
          - by.javaguru.jdmik6.vacationservice.exception.ProfilerUpdateRejectException
          - by.javaguru.jdmik6.vacationservice.exception.BudgetAllocationRejectException
          - by.javaguru.jdmik6.vacationservice.exception.ResourcesCheckRejectException
          - by.javaguru.jdmik6.vacationservice.exception.StabilityMechanismException
    instances:
      accounting-service:
        base-config: default
      resources-service:
        base-config: default
      profiler-service:
        base-config: default

properties:
  used: "Git-Vacation-application-properties"
